name: Build PDF and commit to the gh-pages branch

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - name: Cachix
      uses: cachix/cachix-action@v6
      with:
        name: yurrriq
        skipPush: true
    - name: Clone gh-pages branch
      run: |
        git clone --quiet --branch gh-pages --depth 1 https://x-access-token:"$GITHUB_TOKEN"@github.com/"$GITHUB_REPOSITORY".git site
        git -C site config user.name github-actions
        git -C site config user.email github-actions@users.noreply.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build PDF
      run: cp -vr $(nix-build --no-out-link)/* site/
    - name: Commit to gh-pages
      run: |
        git -C site add --all .
        git -C site commit -m 'Publish to GitHub Pages'
        git -C site push --quiet https://x-access-token:"$GITHUB_TOKEN"@github.com/"$GITHUB_REPOSITORY".git gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
